name: deploy

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build_and_push_to_docker_hub:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to Docker
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Push to Docker Hub
      uses: docker/build-push-action@v2
      with:
        push: true
#       название image (выполни команду docker images)
        tags: nickita98/cicd_pipeline:latest
        
  deploy:
      name: Deploy the app
      runs-on: ubuntu-latest
      needs: build_and_push_to_docker_hub
      steps:
      - name: Execute remote ssh commands to deploy
        uses: appleboy/ssh-action@master
        with:
#          Указать IP сервера
          host: ${{ secrets.HOST }}
#          Указать имя пользователя под которым зайти на сервер
          username: ${{ secrets.USER }}
#         Указать публичный ssh key (id_rsa_docker_hub.pub) полученный командой
#         ssh-keygen -t rsa -b 4096 -C “nickita_98@mail.ru"
          key: ${{ secrets.SSH_KEY }}
          script: |
            sudo docker stop main_container
            sudo docker system prune -a -f
            sudo docker pull malyshkoa2/netology-lesson:latest
            sudo nohup docker run --name main_container -d malyshkoa2/netology-lesson:latest